# Generated by Django 3.0.3 on 2020-03-05 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200304_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='time_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified date'),
        ),
    ]
