# Generated by Django 3.0.3 on 2020-03-05 06:35

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/media/', upload_to=blog.utils.user_directory_path),
            preserve_default=False,
        ),
    ]
